backend:
  name: git-gateway
  branch: main # Substitua pelo nome da branch principal (geralmente 'main' ou 'master')

media_folder: "uploads" # Onde as imagens serão armazenadas no repositório
public_folder: "/uploads" # Onde as imagens serão acessadas no site

collections:
  - name: "páginas" # Nome da coleção
    label: "Páginas"
    files:
      - name: "home"
        label: "Página Inicial"
        file: "index.html" # Arquivo que será editado
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Conteúdo", name: "body", widget: "text" }