backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Páginas"
    files:
      - name: "home"
        label: "Página Inicial"
        file: "index.html"
        fields:
          - { label: "Título do Site", name: "title", widget: "string" }
          - { 
              label: "Seções", name: "sections", widget: "object", 
              fields:
                [
                  { label: "Home - Título", name: "home.heading", widget: "string" },
                  { label: "Home - Conteúdo", name: "home.content", widget: "text" },
                  { label: "Produtos - Título", name: "produtos.heading", widget: "string" },
                  { label: "Produtos - Conteúdo", name: "produtos.content", widget: "text" },
                  {
                    label: "Produtos - Itens",
                    name: "produtos.items",
                    widget: "list",
                    field: { label: "Item", name: "item", widget: "string" }
                  },
                  { label: "Contato - Título", name: "contato.heading", widget: "string" }
                ]
            }