backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "paginas"
    label: "Páginas"
    files:
      - name: "home"
        label: "Página Inicial"
        file: "index.html"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Conteúdo", name: "body", widget: "text" }