title: "AC Moda Fashion"
sections:
  home:
    heading: "Bem-vindo!"
    content: "Encontre as melhores tendências de moda em um só lugar."
  produtos:
    heading: "Nossos Produtos"
    content: "Veja o que temos disponível:"
    items:
      - "Vestidos"
      - "Calças"
      - "Blusas"
  contato:
    heading: "Entre em Contato"